# Generated by Django 5.0.3 on 2024-03-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_remove_customer_age_remove_customer_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
