# Generated by Django 5.0.3 on 2024-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_remove_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=300),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('E', 'Export'), ('I', 'Import'), ('V', 'Vente TFZ')], max_length=1),
        ),
    ]
