# Generated by Django 5.0.3 on 2024-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0004_remove_customer_email_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ICE',
            field=models.IntegerField(default=0),
        ),
    ]
