# Generated by Django 5.0.3 on 2024-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0005_customer_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nbre_GB',
            field=models.IntegerField(default=0),
        ),
    ]
