# Generated by Django 5.0.3 on 2024-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0007_invoice_invoice_number_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CIF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='CP',
            field=models.IntegerField(default=0),
        ),
    ]
