# Generated by Django 5.0.3 on 2024-04-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0008_customer_cif_customer_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order_number',
            field=models.CharField(default=0, max_length=200000000),
        ),
        migrations.AddField(
            model_name='article',
            name='remorque_number',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000),
        ),
    ]
