# Generated by Django 5.0.3 on 2024-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0009_article_order_number_article_remorque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(default='', max_length=200000000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remorque_number',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='order_number',
            field=models.CharField(default='', max_length=20000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='remorque_number',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
