# Generated by Django 5.0.3 on 2024-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0010_invoice_order_number_invoice_remorque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_nbre_gb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_poid_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
