# Generated by Django 5.0.3 on 2024-05-05 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0011_invoice_total_nbre_gb_invoice_total_poid_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_date_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('commande_number', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('ref', models.CharField(default='', max_length=200000000)),
                ('designation', models.CharField(default='', max_length=200000000)),
                ('Qt', models.IntegerField(default=0)),
                ('Prix', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Montant_HT', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Total_HT', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Total_TTC', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Poids', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fact_app.customer')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
