# Generated by Django 5.0.3 on 2024-05-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0012_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
    ]
