# Generated by Django 5.0.3 on 2024-05-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0013_remove_commande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('Qt', models.IntegerField(default=0)),
                ('Prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Montant_HT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_HT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_TTC', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Poids', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fact_app.commande')),
            ],
        ),
    ]
