# Generated by Django 5.0.3 on 2024-05-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0014_commandeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeitem',
            options={'verbose_name': 'CommandeItem', 'verbose_name_plural': 'CommandeItems'},
        ),
        migrations.RemoveField(
            model_name='commandeitem',
            name='Total_HT',
        ),
        migrations.RemoveField(
            model_name='commandeitem',
            name='Total_TTC',
        ),
        migrations.RemoveField(
            model_name='commandeitem',
            name='commande',
        ),
    ]
