# Generated by Django 5.0.3 on 2024-05-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0015_alter_commandeitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandeItem',
        ),
    ]
