# Generated by Django 5.0.3 on 2024-05-20 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0016_delete_commandeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=200000000)),
                ('designation', models.CharField(default='', max_length=200000000)),
                ('Qt', models.IntegerField(default=0)),
                ('Prix', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Poids', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Montant_HT', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fact_app.commande')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fact_app.customer')),
            ],
            options={
                'verbose_name': 'CommandeItem',
                'verbose_name_plural': 'CommandeItems',
            },
        ),
    ]
